# Generated by Django 5.2.15 on 2026-06-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_movie_review_per_user',
        ),
    ]
