# Generated by Django 5.2.15 on 2026-06-24 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
        ('reviews', '0002_remove_review_unique_movie_review_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('movie', 'review_user'), name='unique_movie_review_per_user'),
        ),
    ]
