# Generated by Django 5.2.15 on 2026-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storyline', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('release_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platforms', models.ManyToManyField(related_name='movies', to='movies.streamingplatform')),
            ],
        ),
    ]
