# Generated by Django 5.2.15 on 2026-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingplatform',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='streamingplatform',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
