# Generated by Django 5.2.15 on 2026-07-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_streamingplatform_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
    ]
